### Sensors
sensor:
  # Kitchen Temperate
  - platform: homeassistant
    entity_id: sensor.temperature_kitchen_temperature
    id: kitchen_temperature
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%d° / %d°"
            args: [ '(int)round(id(kitchen_temperature).state)', '(int)round(x)' ]

  - platform: homeassistant
    id: home_thermostat
    entity_id: climate.airconditioner
    attribute: temperature
    on_value:
      - lvgl.spinbox.update:
          id: spinbox_id
          value: !lambda return x;

### Binary sensors
binary_sensor:
  # Towels
  - platform: homeassistant
    id: towels
    entity_id: switch.towel
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: heated_towel_button
          state:
            checked: !lambda return x;
  - platform: status
    name: Status sensor

###Text sensors for weather status
text:
  - platform: lvgl
    name: fr_cond_icon
    widget: lbl_weather_forecast_condition_icon
    mode: text
  - platform: lvgl
    name: fr_cond_name
    widget: lbl_weather_forecast_condition_name
    mode: text