sensor:

  # Lounge Temperature
  - platform: homeassistant
    entity_id: sensor.airconditioner_air_temperature
    id: lounge_temperature
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%d° / %d°"
            args: [ '(int)round(x)', '(int)round(id(lounge_temperature).state)' ]



binary_sensor:

  # Aircon
  - platform: homeassistant
    id: air_conditioner
    entity_id: climate.airconditioner
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: aircon_button
          state:
            checked: !lambda return x;
