# http://materialdesignicons.com/cdn/7.4.47/

# Define icons used
font:
  - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
    id: icon_font
    size: 36
    bpp: 4
    glyphs: [
      "\U000F0335",  # mdi-lightbulb
      "\U000F042B",  # mdi-printer-3d
      "\U000F0D43",  # mdi-air-filter
      "\U000F1051",  # mdi-led-strip-variant
      "\U000F03D7",  # mdi-package-variant-closed
      "\U000F07D6",  # mdi-led-strip
      "\U000F00AC",  # mdi-blind
      "\U000F1A4C",  # mdi-lightbulb-night
      "\U000F1087",  # mdi-router-network
      "\U000F036B",  # mdi-message-video
      "\U000F0614",  # mdi-application-outline
      "\U000F07C9",  # mdi-forklift
      "\U000F02AB",  # mdi-gmail
      "\U000F04B1",  # mdi-slack
      "\U000F0633",  # mdi-command
      "\U000F15A2",  # mdi-ladder
      "\U000F0594", # clear-night
      "\U000F0590", # cloudy
      "\U000F0F2F", # exceptional
      "\U000F0591", # fog
      "\U000F0592", # hail
      "\U000F0593", # lightning
      "\U000F067E", # lightning-rainy
      "\U000F0595", # partlycloudy
      "\U000F0596", # pouring
      "\U000F0597", # rainy
      "\U000F0598", # snowy
      "\U000F067F", # snowy-rainy
      "\U000F0599", # sunny
      "\U000F059D", # windy
      "\U000F059E", # windy-variant
      "\U000F14E4", # sunny-off
      
      ]

# Map icons to names
substitutions:
  lightbulb:      "\U000F0335"
  printer:        "\U000F042B"
  aircon:         "\U000F0D43"
  ledstrip:       "\U000F1051"
  package:        "\U000F03D7"
  lights:         "\U000F07D6"
  blind:          "\U000F00AC"
  nightlight:     "\U000F1A4C"
  network:        "\U000F1087"
  videocall:      "\U000F036B"
  application:    "\U000F0614"
  forklift:       "\U000F07C9"
  gmail:          "\U000F02AB"
  slack:          "\U000F04B1"
  command:        "\U000F0633"
  ladder:         "\U000F15A2"
#weather
  clear-night:    "\U000F0594", # clear-night
  cloudy:         "\U000F0590", # cloudy
  partlycloudy:   "\U000F0595", # partlycloudy
  pouring:        "\U000F0596", # pouring
  rainy:          "\U000F0597", # rainy
  sunny:          "\U000F0599", # sunny
  windy:          "\U000F059D", # windy
 
