# http://materialdesignicons.com/cdn/7.4.47/

# Define icons used
font:
  - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
    id: icon_font
    size: 36
    bpp: 4
    glyphs: [
      "\U000F0335",  # mdi-lightbulb
      "\U000F042B",  # mdi-printer-3d
      "\U000F0D43",  # mdi-air-filter
      "\U000F1051",  # mdi-led-strip-variant
      "\U000F03D7",  # mdi-package-variant-closed
      "\U000F07D6",  # mdi-led-strip
      "\U000F00AC",  # mdi-blind
      "\U000F1A4C",  # mdi-lightbulb-night
      "\U000F1087",  # mdi-router-network
      "\U000F036B",  # mdi-message-video
      "\U000F0614",  # mdi-application-outline
      "\U000F07C9",  # mdi-forklift
      "\U000F02AB",  # mdi-gmail
      "\U000F04B1",  # mdi-slack
      "\U000F0633",  # mdi-command
      "\U000F15A2",  # mdi-ladder
      
      ]

# Map icons to names
substitutions:
  lightbulb:      "\U000F0335"
  printer:        "\U000F042B"
  aircon:         "\U000F0D43"
  ledstrip:       "\U000F1051"
  package:        "\U000F03D7"
  lights:         "\U000F07D6"
  blind:          "\U000F00AC"
  nightlight:     "\U000F1A4C"
  network:        "\U000F1087"
  videocall:      "\U000F036B"
  application:    "\U000F0614"
  forklift:       "\U000F07C9"
  gmail:          "\U000F02AB"
  slack:          "\U000F04B1"
  command:        "\U000F0633"
  ladder:         "\U000F15A2"
