# Backlight
light:
  - platform: gpio
    id: backlight
    pin: 
      ch422g: ch422g_hub
      number: 2
    restore_mode: ALWAYS_ON
    internal: true

# Screensaver Presence Trigger
binary_sensor:
  - platform: homeassistant
    id: presence
    entity_id: binary_sensor.office_presence
    on_press:
      - lvgl.resume:
      - delay: 10ms
      - light.turn_on: backlight
      - logger.log: "Screensaver is turned off"

    on_release:
      - light.turn_off: backlight
      - lvgl.pause:
          show_snow: true
      - logger.log: "Screensaver is turned on"
