# Backlight
switch:
  - platform: gpio
    id: backlight
    pin: 
      ch422g: ch422g_hub
      number: 2
    restore_mode: ALWAYS_ON
    internal: true

  - platform: template
    name: Antiburn
    id: switch_antiburn
    icon: mdi:television-shimmer
    optimistic: true
    entity_category: "config"
    turn_on_action:
      - logger.log: "Starting Antiburn"
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:
      - lvgl.pause:
          show_snow: true
    turn_off_action:
      - logger.log: "Stopping Antiburn"
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:

# Screensaver Presence Trigger
binary_sensor:
  - platform: homeassistant
    id: presence
    entity_id: binary_sensor.bus_presence
    on_press:
      - lvgl.resume:
      - delay: 10ms
      - switch.turn_on: backlight
      - logger.log: "Screensaver is turned off"

    on_release:
      - switch.turn_off: backlight
      - lvgl.pause:
          show_snow: true
      - logger.log: "Screensaver is turned on"

# Screensaver Timeout
number:
  - platform: template
    name: LVGL Screen timeout
    optimistic: true
    id: display_timeout
    unit_of_measurement: "s"
    initial_value: 45
    restore_value: true
    min_value: 10
    max_value: 180
    step: 5
    mode: box
    